### ISSUE TITLE
JS Runtime Exception with BalzorFabric DropDown

### ISSUE THREAD

**Issue by sowsan** [limefrogyank/BlazorFabric#102]
Getting JS Runtime Exception when I click on the dropdown. Any ideas ?

![image](https://user-images.githubusercontent.com/11544153/73188534-0564a780-40f1-11ea-9726-03c5afe908a1.png)

**Comment by limefrogyank** [comment]
Top is cutoff… but you may be missing focusZone.js or baseComponent.js?  Hard to tell.  Clearing cookies between an update is also a good idea.

**Comment by sowsan** [comment]
Thank you. It seems both of those JS files loaded. Cleared the cookie and the same issue. Getting an error while loading the page as well when I use the dropdown control. Am I missing anything? I have copy pasted the docs/content folder the repo to my project.

![image](https://user-images.githubusercontent.com/11544153/73196415-8de94500-40fd-11ea-9b7f-351b3f880a49.png)

scripts loaded
![image](https://user-images.githubusercontent.com/11544153/73196606-e0c2fc80-40fd-11ea-8f8d-9a27ce7c3968.png)

**Comment by limefrogyank** [comment]
Mismatching Nuget versions?  Everything updated to 2.2.0?  

I changed baseComponent.ts's `registerResizeEvent` function to send two arguments back to the .NET code.  See if your baseComponent.ts (that you see in your browser window) has this method:

```
export function registerResizeEvent(dotnetRef: DotNetReferenceType, functionName: string) : string {
        var guid = Guid.newGuid();
        eventRegister[guid] = debounce((ev: UIEvent) => {
            dotnetRef.invokeMethodAsync(functionName, window.innerWidth, innerHeight);
        }, 100, { leading: true });
        window.addEventListener("resize", eventRegister[guid]);
        return guid;
    }
```
If not, somehow you've got the old version still.

The important part is this part: `dotnetRef.invokeMethodAsync(functionName, window.innerWidth, innerHeight);`

**Comment by limefrogyank** [comment]
Oh, I just noticed... don't use the docs/content folder... that hasn't been updated recently.  Use 
https://github.com/limefrogyank/BlazorFabric/tree/54b3833b478de1c3614fb72f430bb9ca1aaa6cd6/Demo/BlazorFabric.Demo.ServerSide 
and
https://github.com/limefrogyank/BlazorFabric/tree/54b3833b478de1c3614fb72f430bb9ca1aaa6cd6/Demo/BlazorFabric.Demo.Shared

for up-to-date samples.

We use the doc folder to host a client-side running demo.  
if you want to

**Comment by sowsan** [comment]
Sorry for my lack of understanding :) 

Where is the _contents/ resources physically located referred in the _Host.cshtml file? I am not finding a _contents folder in the wwwroot directory in the service side sample. All I need is few specific controls in my app.

**Comment by sowsan** [comment]
Nevermind noticed that _content folder was created when I refer the BlazorFabric control. All good now :) Thank you so much!

**Comment by limefrogyank** [comment]
Yeah, hopefully you are creating your blazor app with `dotnet new ...` or the VS templates.  After that you can just install only the components you want with Nuget.  They're all individual packages.  They'll automatically bring in any components they depend on.  The only hard part is figuring out which js and css assets you need to include in your html file.
