### ISSUE TITLE
Persona image source options

### ISSUE THREAD

**Issue by sowsan** [limefrogyank/BlazorFabric#104]
Any way that we can render the persona component with images without a source URL? In my case, I am getting the images in bytes/base64string format.

**Comment by limefrogyank** [comment]
`Persona` uses `Image` for the image.  And `Image` just uses a plain `<img>` tag with `src` attribute to show images.  So you should be able to show base64 data.  Just format it properly:

https://stackoverflow.com/questions/8499633/how-to-display-base64-images-in-html

**Comment by sowsan** [comment]
sweet. worked like a charm :)
