### ISSUE TITLE
Text component not working

### ISSUE THREAD

**Issue by sowsan** [limefrogyank/BlazorFabric#117]
Tags cannont contain attributes.

![image](https://user-images.githubusercontent.com/11544153/76245041-94490180-6211-11ea-896b-9ddee8003890.png)

nuget version 

![image](https://user-images.githubusercontent.com/11544153/76245114-b2166680-6211-11ea-910d-9999c393c7fb.png)

Using server-side blazor on netcoreapp3.1

**Comment by Eweol** [comment]
Hey @sowsan,
on your first Picture it looks like the Text-Component itself wasn't found
do you use BlazorFabric Namespace in "_Imports.razor"?

**Comment by sowsan** [comment]
Thank you, @Eweol . Yes, its included in the _imports.razor @using BlazorFabric.  There is no problem to use this control outside an inline c# snippet though. (picture below)

![image](https://user-images.githubusercontent.com/11544153/76868723-b4924500-683d-11ea-9df0-85d87b938244.png)

**Comment by Eweol** [comment]
Ahhh ok
Can you try `BlazorFabric.Text`?

Mit freundlichen Grüßen / Best regards

Lukas Frensel

________________________________

**Comment by Eweol** [comment]
Ah ok,
Maybe you can try `BlazorFabric.Text`?

**Comment by sowsan** [comment]
@Eweol  yes that worked :). Thank you!
