### ISSUE TITLE
Input-Fields in Panel are not clickable on first open

### ISSUE THREAD

**Issue by Eweol** [limefrogyank/BlazorFabric#119]
Steps to reproduce:
-> add an input-field to a Panel (doesn't matter if plain html or blazorcomponent or blazrofabricComtonent)
-> run application
-> open panel and try to enter input field (will fail you can click into but you cannot type and you also don't see cursor)
-> close panel
-> reopen panel (now everything works like expected)

**Comment by limefrogyank** [comment]
Ouch, that is bad.  Definitely a focus stealing problem.  

I can take a look soon.  All of the classes I am teaching are done and finals are done.  I have a week of breathing room before the next term.  We should fix this one and then publish the new version soon.

**Comment by limefrogyank** [comment]
We'll push this fix with the next release today or tomorrow!
