### ISSUE TITLE
[Feature Request] Basic Toggles

### ISSUE THREAD

**Issue by Eweol** [limefrogyank/BlazorFabric#23]
Hey @limefrogyank ,

Very big Thank you for your Work, I realy like it and it make fun to see progress of this beautifull project. 
Is there a chance that you include Basic Toggles in one of the next releases?
It would be realy nice, when I could use them in my Blazor-PWA.

**Comment by limefrogyank** [comment]
Seems like an easy one to do...

Although it contains `KeytipData`... which I haven't done yet... and also don't know how they work.  At least, it doesn't seem to work on the Office UI Fabric controls page.  I assume the Keytip popup is supposed to show up when you hold Alt or Ctrl or Shift or some combination... but it didn't work for me. 

Ok, I'll look into this next and get it done.  Maybe this weekend.

(Leaving this here for now)
https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Toggle/Toggle.base.tsx
https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/KeytipData/KeytipData.tsx
https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/KeytipLayer/KeytipLayer.base.tsx

**Comment by limefrogyank** [comment]
ah, didn't read the docs well.  It's Alt-Windows key together to show `Keytip`

**Comment by Eweol** [comment]
Thank you very much

Ah now I allso know KeyTip feature. 
Nice Function. 
Thank You XD

**Comment by Eweol** [comment]
By The way I searched the ResponsiveLayout in Nuget but didn't found it.
Is it included in another Nuget-Package?

**Comment by limefrogyank** [comment]
`Toggle` added with https://github.com/limefrogyank/BlazorFabric/commit/79bb890cb6bc0bcfa5c6fada1cf025724d8fc0d0

`Keytip` doesn't work yet but you don't need it for toggle functionality.  I'll push some new Nuget packages later today or tomorrow.

**Comment by limefrogyank** [comment]
Ok, packages up.  I didn't want to wait for `Keytip` because it looks complicated

**Comment by Eweol** [comment]
Thank you
