### ISSUE TITLE
Wrong style TextField-Description

### ISSUE THREAD

**Issue by Eweol** [limefrogyank/BlazorFabric#29]
The description line under TextField seems to have wrong css style

**Comment by limefrogyank** [comment]
When I did these, the Fabric team was in the middle of converting the old style to Fluent... I was looking in multiple files to piece together the correct style.  Seems I got it wrong.  I'll check again.

**Comment by Eweol** [comment]
I recognized it by implementing Validation and compared it with  [this](https://developer.microsoft.com/en-us/fabric#/controls/web/textfield)

**Comment by limefrogyank** [comment]
Ok, done.  Style was missing and the font size styles had been changed.  I updated style.css in BaseComponents as well.

**Comment by limefrogyank** [comment]
https://github.com/limefrogyank/BlazorFabric/commit/041d6a058ccdeb1b2e4e5695df85a77c087d733e
