### ISSUE TITLE
Mask Properties on TextField

### ISSUE THREAD

**Issue by Eweol** [limefrogyank/BlazorFabric#30]
Mask Properties on Textfiel should be deleted and moved to a MaskTextField-Component

**Comment by Eweol** [comment]
Will have a look at it later on

**Comment by Eweol** [comment]
Mask-Properties are out of TextField now  #35 
Next will have a look to implement MaskTextField as own compontent

**Comment by limefrogyank** [comment]
I just published an update to the demo and the TextField page is crashing everything... 
Seems like it was the MaskChar prop still in the demo.

I got rid of them and republished. https://github.com/limefrogyank/BlazorFabric/commit/1eea6aa2f4b6de5e85102f379628ecf4a30cbbb9

**Comment by Eweol** [comment]
Sry my bad I forgot to take care about the demo regarding Mark-Properties

**Comment by Eweol** [comment]
Will split up the ticket
This will be closed because Mask-Properties are not part of normal TextField anymore
For MaskTextField-Implementation there will be the ticket [#51](https://github.com/limefrogyank/BlazorFabric/issues/51)
