### ISSUE TITLE
Rating should be embedded in FocusZone

### ISSUE THREAD

**Issue by Eweol** [limefrogyank/BlazorFabric#36]
If FocusZone-Component is ready Rating should be embedded in it
AriaLabel needs to be implemented up to then

**Comment by limefrogyank** [comment]
Misread FocusZone for FocusTrapZone.  I want to create the FocusZone eventually...

**Comment by limefrogyank** [comment]
https://github.com/limefrogyank/BlazorFabric/commit/ff7c0f8b081e4e3d68c71372f459b07b5af029c9

Done!  One small issue:

https://github.com/limefrogyank/BlazorFabric/issues/43
