### ISSUE TITLE
messagebar css class in messagebar.css

### ISSUE THREAD

**Issue by Eweol** [limefrogyank/BlazorFabric#49]
Messagebar.css force font-weight for button up to 600 which should not be needed
maybe there is a problem with relation between messagebar and defaultbutton

**Comment by limefrogyank** [comment]
I think it's a flaw in the order of class names here:
https://github.com/limefrogyank/BlazorFabric/blob/master/src/BlazorFabric.Button/ButtonBase.cs#L183

`mediumFont` should be first.  I think the rest are fine.  Feel free to test and update if you have the time.  I can't get to it until Friday.

**Comment by Eweol** [comment]
Problem was wrong usage of Button-Parameters. I used ChildComponent instead of Text
