### ISSUE TITLE
MessageBar-Button style differ Server-Side / Client-Side

### ISSUE THREAD

**Issue by Eweol** [limefrogyank/BlazorFabric#50]
Why ever the Button style of Messagebar differ between Server-Side an Client-Side

**Comment by limefrogyank** [comment]
Clear your browser cache? Also, the latest VS preview gets unstable for me and eventually fails to update certain files when debugging via iisexpress. I've had to restart vs to fix it.

Sent from my Windows 10 device

**Comment by Eweol** [comment]
@limefrogyank , Thank you for help but reason was much easier than this
I forgot to add "button-messagebar.css" to _Host.cshtml file XD
