### ISSUE TITLE
Should we target AspNetCore 3.1?

### ISSUE THREAD

**Issue by limefrogyank** [limefrogyank/BlazorFabric#67]
@Eweol and anyone else who is using this library:

AspNetCore 3.1 is still in preview... however, there is some functionality that would be extremely useful.  In 3.1, you can apply 
```
@eventname:stopPropagation="true" @eventname:preventDefault="true"
```
to elements.  I'm sure there are others.  When would be a good time to target 3.1?  Client-side is still considered experimental and won't be official until 3.1.  However, server-side is fully supported with 3.0.  

Personally, although I would love to use the newest features, I'd say keeping it at 3.0 until later next year would be the right thing to do.  At a certain point, we'd freeze development on v1.X of these components and start targeting 3.1 and move BlazorFabric's version number to 2.0.  

Any comments?

**Comment by Eweol** [comment]
I like the idea to go to 3.1 also because of partial class support for components but I also think we should wait a little bit.
Maybe there is a nice prev. in begin of next year where we can switch to but for now I would also wait.
I also like the idea to go to 2.0 with .Net-Core 3.1

**Comment by limefrogyank** [comment]
Speak of the devil:
https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-core-3-1/

I guess we can update now.  I had assumed they would wait for client-side blazor to be finished, but they have not.  Especially since this is an LTS release, we should just make all new components target aspnetcore 3.1 and upgrade our version number to v2 from now on.

**Comment by Eweol** [comment]
Oh no
I hoped so much that they will finish up Blazor client side with 3.1.

**Comment by Eweol** [comment]
Ok than we will do it like described above and begin upon now with V2.0 and asp.Net core 3.1

**Comment by Eweol** [comment]
Have the feeling, that Demo becomes very slow after upgrading to 3.1 and .Net-Standart 2.1 Will make some tests again to find out what of that make it slow.

**Comment by Eweol** [comment]
Maybe also @limefrogyank can have a look at the branch and give feedback

branch is: features/dotNetUpgrade

**Comment by limefrogyank** [comment]
So far it doesn't seem bad.  I've only tried client-side but I'll keep playing with it.
