### ISSUE TITLE
Default Namespace

### ISSUE THREAD

**Issue by vertonghenb** [limefrogyank/BlazorFabric#7]
Currently a lot of namespaces exist, which makes a lot of sense in the folder structure. However it would be nice if we set the namespace to 1 e.g.
```cs
@namespace BlazorFabric
```

This way it's much cleaner to use the components in other libs.

**Comment by limefrogyank** [comment]
https://github.com/limefrogyank/BlazorFabric/commit/d833f6fab5b0a8ebd860439634488a9e7767ca90

This commit changed the namespace.  Now we have the awful possibility of `List` from `BlazorFabric` conflicting with `List` from `System.Collections.Generic`.  Maybe I'll change the name for our `List` to something else.

**Comment by limefrogyank** [comment]
FYI, since Blazor doesn't seem to do the `internal` accessibility (I couldn't get it to work).  Anything I didn't want polluting the `BlazorFabric` namespace I ended up putting in `BlazorFabric.{ComponentName}Internal`
