### ISSUE TITLE
TextField multiline resize icon doesn't update

### ISSUE THREAD

**Issue by limefrogyank** [limefrogyank/BlazorFabric#73]
To reproduce:
1. Go to `TextField` demo page and scroll to multiple multiline `TextField`s.  
2. Resize the top one.
3. While the current resize icon will move with the mouse, the next `TextField`'s multiline icon will not reposition itself with the new `TextField` position.

**Comment by limefrogyank** [comment]
Before:
![image](https://user-images.githubusercontent.com/7821384/70344308-3a99fb00-180e-11ea-948d-4fb747fcc174.png)

After:
![image](https://user-images.githubusercontent.com/7821384/70344339-53a2ac00-180e-11ea-8a39-7df5b04d1a1a.png)

**Comment by Eweol** [comment]
I tryed on Server / Client-Side but I cannot reproduce that
Maybe some more information?

**Comment by limefrogyank** [comment]
Ah, I only tested in Edge Canary.  It seems to work fine in Edge Beta and Chrome.  It must be an Edge Canary bug...
