### ISSUE TITLE
ProgressIndicator with Percentage is broken

### ISSUE THREAD

**Issue by Eweol** [limefrogyank/BlazorFabric#74]
After .Net-Core upgrade to 3.1 and upgrade to .Net-Standard2.1 the ProgressIndicator seems to be broken on Server-Side Demo.

Maybe there is only an StateHasChanged to much or something like that.

**Comment by limefrogyank** [comment]
I don't see a problem.  I have pushed the dotnet upgrade branch to master already.  I tried in Debug and Release mode with both Edge Canary and Chrome and they both seem to work fine in server-side mode.

**Comment by Eweol** [comment]
Is an LSB problem
Will fix it tomorrow
