### ISSUE TITLE
RichTextEditor for Example-Code on DemoPages

### ISSUE THREAD

**Issue by Eweol** [limefrogyank/BlazorFabric#79]
Hey @limefrogyank,
Do you think it is doable to make the RichTextEditor also ReadOnly so that we can provide there example-code for demo-pages?

**Comment by limefrogyank** [comment]
Yes, I can do that.  I'm working on solving #81 right now.  I'll add more properties after that.

**Comment by limefrogyank** [comment]
Readonly works, but I'm having problems with `CommandBar` now.  For pages where Readonly is not being toggled on and off, `RichTextEditor` is fine.

**Comment by limefrogyank** [comment]
FYI, the `RichTextEditor` doesn't seem to have any problems with `CommandBar` anymore.
