### ISSUE TITLE
Compound Button style is broken

### ISSUE THREAD

**Issue by Eweol** [limefrogyank/BlazorFabric#84]
Hey @limefrogyank,
Do you think every button should have ability to be a compound button?
Than I would only add the right styling for that and we don't create a Compound-button-Component and use instead the Secondary Line as indicator for right css
otherwise I would create a Compound-button-component and delete ability for other buttons to use Secondary line

**Comment by limefrogyank** [comment]
I think the CompoundButton react component is new.  When I started, it wasn't separated like it is now.  We can refactor to create a separate CompoundButton and move the Secondary property to this new control.

**Comment by limefrogyank** [comment]
#17 related
