### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by NPadrutt** [limefrogyank/BlazorFabric#9]
Hi
I wanted to checkout the demo, but the page stays on the "Loading.." page for me. I checked the Dev Tools and I have  loads of 403 messages coming back.

![image](https://user-images.githubusercontent.com/1764367/64943731-d4d04f80-d86c-11e9-9013-f1f80c991f4e.png)

**Comment by limefrogyank** [comment]
Hmm, it was working for me last week. I'll check it tomorrow...

**Comment by NPadrutt** [comment]
I just checked another project and had the same issue, but it works on my phone. so it might have to do with my company security settings..

**Comment by limefrogyank** [comment]
Yeah, it's the firewall blocking .dll files.   Some antivirus will do this, too.  This is the thread that talks about it and possible future plans to correct it:
https://github.com/aspnet/AspNetCore/issues/5477

**Comment by limefrogyank** [comment]
FYI, this would be no problem at all on a server-side Blazor app.  It only gets the js and css files.

**Comment by limefrogyank** [comment]
Reopening because I just noticed a workaround... maybe I'll implement it next.

**Comment by NPadrutt** [comment]
Oh it is a server side project? I thought I saw a mono.wasm and assumed it's a wasm version.

**Comment by limefrogyank** [comment]
No, the demo is client-side... but these controls work on server-side blazor just fine, too.  (Except for `List` which has performance issues right now.)

**Comment by limefrogyank** [comment]
Want to try the demo again on your work PC?  I implemented the workaround and I'm curious to know if the extension change from .dll to .blazor is enough to circumvent the firewall.

https://blazorfabric.azurewebsites.net/

**Comment by NPadrutt** [comment]
nice, that works! :)
