### ISSUE TITLE
For small screens ContextMenu should display in responsive design

### ISSUE THREAD

**Issue by Eweol** [limefrogyank/BlazorFabric#92]
For small screens the button menu should be rendered in a Callout instead of an ContextMenu

**Comment by limefrogyank** [comment]
Is this new in the React controls?  What would a plain Callout do for small screens?  (ContextMenu already renders inside a Callout)

**Comment by Eweol** [comment]
Don't know since when this exists
I also was also surprised when I saw it today
I will share screenshots

**Comment by Eweol** [comment]
Small screen: ![](https://i.imgur.com/ErrD6jE.jpg)
Wide screen: ![](https://i.imgur.com/tfDNSI6.jpg)

**Comment by limefrogyank** [comment]
Ah, it's a `ContextualMenu` piece:

https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.base.tsx#L272

**Comment by Eweol** [comment]
Ah OK

**Comment by limefrogyank** [comment]
For small screens, `Dropdown` actually displays a `Panel`.  So we need to implement a way for the components to differentiate the screen width.  I'm refactoring the `ResponsiveLayout` to be more simple (and not need complicated javascript).
