### ISSUE TITLE
Question: Consolidate javascript and import css?

### ISSUE THREAD

**Issue by limefrogyank** [limefrogyank/BlazorFabric#95]
There are one or two components that have a lot of javascript.  `Callout` is one because of measuring position.  However, the rest at most do some basic event registration... which could be made generic (maybe) and placed into baseComponent.ts.   This would remove a lot of javascript dependencies.

I don't think we should consolidate css (except maybe for buttons), but we could use some import statements that make components import css files from components they depend on.  This would make sure that if someone has only downloaded the `DatePicker` nuget package, they can include datePicker.css and then not worry about all of the other css dependencies.

Can you think of any drawbacks to this?

**Comment by limefrogyank** [comment]
For the record, import statements for CSS were bad.  Except for very specific cases (like consolidating all the button css), it seems to easy to create what I think were loops that locked up the debugger on the browser.

**Comment by Eweol** [comment]
For record. 
This will be partly fixed in V3.
In V3 all css files are dropped and styles will be provided by ComponentStyle

**Comment by limefrogyank** [comment]
I think we're done with this.  It's not automatic yet, but there's a simple way to consolidate javascript now.  (see TypescriptCommands.txt)
